transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work


vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/DCMotor {C:/Users/catsr/source/repos/SCARA_robot/hdl/DCMotor/DCMotor.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/DCMotor {C:/Users/catsr/source/repos/SCARA_robot/hdl/DCMotor/dc_cnt.sv}

vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions/Int15BitToDouble.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions/FloatToDouble.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions/Fixed13BitToFloat.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions/Fixed13BitToDouble.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions/DoubleToInt15Bit.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions/DoubleToInt9Bit.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Conversions/DoubleTo32BitFixed.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Atan2/synthesis {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Atan2/synthesis/Atan2.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/SqRoot {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/SqRoot/SqRoot.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/SinCos {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/SinCos/Cosine.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/SinCos {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/SinCos/Sine.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/MultiplierFP {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/MultiplierFP/MultiplierFP.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/Inverter {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/Inverter/Inverter.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/FloatAdder {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/FloatAdder/FloatAdder.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/Adder {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/Adder/Adder.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/hex_decoder.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db/mult_jbo.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db/mult_rio.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db/mult_h4o.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db/mult_bbo.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db/mult_f4o.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db/mult_jvs.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db/mult_2rr.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db/mult_8rr.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db/mult_lsr.v}
vlog -vlog01compat -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/db/mult_nsr.v}
vlib Computer_System
vmap Computer_System Computer_System
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/Computer_System.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_pll_0.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_fifo_FPGA_to_HPS.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_System_PLL.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_up_avalon_reset_from_locked_signal.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_System_PLL_sys_pll.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_Onchip_SRAM.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_ARM_A9_HPS.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_ARM_A9_HPS_hps_io.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/hps_sdram.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_mem_if_hhp_qseq_synth_top.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_acv_hard_addr_cmd_pads.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_acv_hard_io_pads.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_acv_hard_memphy.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_acv_ldc.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_altdqdqs.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_clock_pair_generator.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/hps_sdram_p0_generic_ddio.v}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions/SineTh2.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions/K1.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions/ForwardKinematics.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions/CosineTh2.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions/CalculateSteps.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions/CalculateAngles.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Functions/Arctan2.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/BasicBlocks/Counter {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/BasicBlocks/Counter/Counter.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/BasicBlocks/ClockTimer {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/BasicBlocks/ClockTimer/ClockTimer.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/SqRoot {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/SqRoot/SquareRoot.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/DoubleMultiplier {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/DoubleMultiplier/DoubleMultiply.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/DoubleAdder {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/Arithmetic/DoubleAdder/DoubleAdder.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/StepperMotor/StepperFPGA/stepper_motor {C:/Users/catsr/source/repos/SCARA_robot/hdl/StepperMotor/StepperFPGA/stepper_motor/stp_counter.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2 {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA_controller_v2/ScaraController.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/StepperMotor/StepperFPGA/stepper_motor {C:/Users/catsr/source/repos/SCARA_robot/hdl/StepperMotor/StepperFPGA/stepper_motor/stepper_motor.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/DE1_SoC_Computer.sv}
vlog -sv -work work +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/State_Interface.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_irq_mapper.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1_rsp_mux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1_rsp_demux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1_cmd_mux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1_cmd_demux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_merlin_burst_adapter_13_1.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_merlin_address_alignment.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_merlin_traffic_limiter.sv}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1_router_002.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_1_router.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_merlin_axi_master_ni.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router_002.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altdq_dqs2_acv_connect_to_hard_phy_cyclonev.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_mem_if_dll_cyclonev.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_mem_if_hard_memory_controller_top_cyclonev.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/altera_mem_if_oct_cyclonev.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/hps_sdram_p0.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/hps_sdram_pll.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_ARM_A9_HPS_hps_io_border.sv}
vlog -sv -work Computer_System +incdir+C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules {C:/Users/catsr/source/repos/SCARA_robot/hdl/FPGA/verilog/Computer_System/synthesis/submodules/Computer_System_ARM_A9_HPS_fpga_interfaces.sv}
vlib Atan2
vmap Atan2 Atan2
vcom -93 -work Atan2 {c:/users/catsr/source/repos/scara_robot/hdl/fpga/verilog/db/ip/atan2/submodules/dspba_library_package.vhd}
vcom -93 -work Atan2 {c:/users/catsr/source/repos/scara_robot/hdl/fpga/verilog/db/ip/atan2/submodules/atan2_cordic_0.vhd}
vcom -93 -work Atan2 {c:/users/catsr/source/repos/scara_robot/hdl/fpga/verilog/db/ip/atan2/submodules/dspba_library.vhd}

